# Generated by Django 2.1.1 on 2018-10-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedio', '0003_auto_20180928_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='episode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
