# Generated by Django 2.1.1 on 2018-10-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedio', '0004_resources_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='episode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
