# Generated by Django 2.1.1 on 2018-10-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedio', '0005_auto_20181012_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='text',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
